[package]
name = "hello_macro_derive"
version = "0.1.0"
authors = ["ke"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
syn = "1.0.40"
quote = "1.0.7"

[lib]
proc-macro = true